### ISSUE TITLE
Fronius Symo Advanced 17.5-3-M missing

### ISSUE THREAD

**Issue by andreas-bulling** [davidusb-geek/emhass-pvlib-database#1]
the above inverter is missing in the database

https://www.fronius.com/de/solarenergie/installateure-partner/technische-daten/alle-produkte/wechselrichter/fronius-symo-advanced/symo-advanced-17-5-3-m

**Comment by davidusb-geek** [comment]
Not possible to add items to the database here. You can open an issue directly in the PVLib github. Closing

**Comment by andreas-bulling** [comment]
done https://github.com/pvlib/pvlib-python/issues/2145

**Comment by andreas-bulling** [comment]
I've contacted the "California Energy Commission" and have requested for the inverter to be added to their database. https://www.energy.ca.gov/programs-and-topics/programs/solar-equipment-lists

That is where pvlib and SAM pull the information from so hopefully the inverter will become available in one of the next updates of these databases/libraries.
