### ISSUE TITLE
Improve string matching / regular expression handling

### ISSUE THREAD

**Issue by andreas-bulling** [davidusb-geek/emhass-pvlib-database#3]
It seems that the input field and search functionality offered by the webapp can only handle a single search term. If I type in "Trina" I get some results (although too many to see whether I am on the right track - see other issue). If I then want to narrow down the results by typing "Trina 425" (the 425W version) it doesn't find a single module anymore. Neither if I type in other numbers.

**Comment by davidusb-geek** [comment]
This issue can very well be merged with the previous one #2

**Comment by andreas-bulling** [comment]
Can be, of course. But given that the other one requires to modify the UI code, but this one only the regular expression (or whatever is used to find the results for a given search term), I thought to report them separately. In the hope that this one can be implemented more quickly.
