### ISSUE TITLE
SolarEdge StorEdge three phase inverter SE8K-RWS48BEN4

### ISSUE THREAD

**Issue by WimGo** [davidusb-geek/emhass-pvlib-database#4]
Request to add my SolarEdge hybrid inverter to the database.
My SolarEdge app reports it as "SolarEdge SE8K-RWS48BEN4"
The datasheet is the PDF below:
https://www.solaredge.com/sites/default/files/se_storedge_three_phase_inverter_datasheet.pdf

**Comment by davidusb-geek** [comment]
Not possible to add items to the database here. You can open an issue directly in the PVLib github. Closing
